kind: pipeline
type: docker
name: awsbuilders-poweron

clone:
  disable: true

steps:
- name: start-aws-instances
  pull: always
  image: amazon/aws-cli
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  commands:
    - aws ec2 start-instances --region eu-north-1 --instance-ids i-01e3d598710a23947

trigger:
  branch:
    include:
    - master
    - cicd
  event:
    include:
    - push
    - pull_request
    - tag

---

kind: pipeline
type: docker
name: compile-clib2

clone:
  depth: 1

workspace:
  path: /opt/code/webkitty

steps:
- name: build-library
  pull: always
  image: walkero/amigagccondocker:ppc-amigaos-gcc11-newclib2
  commands:
  - make -f GNUmakefile.os4 INSTALL_PREFIX=/opt/clib2/clib2 SDK_INCLUDE=/opt/clib2/include

trigger:
  branch:
    include:
    - master
    - cicd
  event:
    include:
    - push
    - pull_request

depends_on:
  - awsbuilders-poweron

node:
  agents: awsbuilders
